### ISSUE TITLE
Instalação

### ISSUE THREAD

**Issue by rafhaeu** [JeanPrad0/laradefault#2]
tem alguma particularidade para usar o projeto ?
subi em meu servidor usei o composer update, ajustei o .env criou as tabelas no banco de dados mais não consigo abrir a pagina de login, somente a do welcome.
obrigado.

**Comment by jeanfprado** [comment]
Não! Configuração padrão do laravel mesmo. Mas para um correto funcionamento precisa-se criar as tabelas e executar as seeds. O comando 
php artisan migrate --seed 

Foi usado??
